### ISSUE TITLE
Android version does not work for SDK 6.x 

### ISSUE THREAD

**Issue by nascado** [appcelerator-archive/ti.udp#5]
We tried to complie the Android version but did not manage it. If anyone be so kind to upload a new complied Android module this would be perfect.

btw: We successfully complied the iOS version, which works now with SDK 6.0.x and iOS 10.2

**Comment by hansemannn** [comment]
Hey @nascado, thanks! Can you do a PR for the recompiled iOS version? I'll do an update to the Android version as well.

**Comment by hansemannn** [comment]
Please check the above PR, thx!

**Comment by nascado** [comment]
Hallo, 

anbei die kompiilierte iOS Version von ti.udp.
Hope this one works, as I have so many versions now.

Grüße

Marco Huppertz
Truchseßstr. 33
D-40625 Düsseldorf

mh@4dmedia.de
tel. +49 172 2125225

**Comment by hansemannn** [comment]
Sorry, cannot see email attachments on Github. Anyway, I just recompiled iOS with 6.0.2.GA as well and drafted the version 1.3.0. Can you please confirm both versions? Danke!
